# Generated by Django 5.2.6 on 2026-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до'),
        ),
    ]
