# Generated by Django 5.2.6 on 2026-02-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_alter_profile_blocked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocked_until',
            field=models.DateTimeField(blank=True, default='1972-01-01 00:00:00', null=True, verbose_name='Заблокирован до'),
        ),
    ]
